//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cdrv4.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class test1
    {
        public int LineId { get; set; }
        public Nullable<System.DateTime> DateofCall { get; set; }
        public Nullable<System.TimeSpan> TimeofCall { get; set; }
        public string TypeofCall { get; set; }
        public string CallingNumber { get; set; }
        public string CalledNumber { get; set; }
    }
}
